/**
 * Regenerates public/demo/** and src/native.ts from the mock-data seed.
 *   pnpm --filter @elixir/demo-assets generate
 * Existing files are kept unless --force is passed, so a hand-placed real photo survives.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { buildSeed } from '@elixir/mock-data';
import { artFor, type ArtInput } from './art';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');
const sheet = process.argv.includes('--sheet');

const seed = buildSeed();
const cats = new Map(seed.categories.map((c) => [c.id, c]));
const jobs = new Map<string, ArtInput>();
for (const p of seed.products) {
  const c = cats.get(p.categoryId);
  if (p.imageUrl && !jobs.has(p.imageUrl)) jobs.set(p.imageUrl, { name: p.name, category: c?.name ?? '', color: c?.color ?? '#868e96', variant: p.variantAttrs?.color });
}
for (const m of seed.menuItems) {
  const c = cats.get(m.categoryId);
  if (m.imageUrl) jobs.set(m.imageUrl, { name: m.name, category: c?.name ?? '', color: c?.color ?? '#868e96' });
}

const browser = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {});
const page = await browser.newPage();
await page.setContent('<canvas id="c" width="320" height="320"></canvas>');

const unmatched: string[] = [];
const names: Array<[string, string]> = [];
let written = 0;
for (const [url, input] of jobs) {
  const { svg, matched } = artFor(input, url);
  if (!matched) unmatched.push(input.name);
  names.push([url, input.name]);
  const out = join(root, 'public', url);
  if (existsSync(out) && !force) continue;
  const dataUrl = await page.evaluate(async (src) => {
    const img = new Image();
    img.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(src)}`;
    await img.decode();
    const c = document.getElementById('c') as HTMLCanvasElement;
    const ctx = c.getContext('2d')!;
    ctx.clearRect(0, 0, 320, 320);
    ctx.drawImage(img, 0, 0, 320, 320);
    return c.toDataURL('image/webp', 0.86);
  }, svg);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, Buffer.from(dataUrl.split(',')[1]!, 'base64'));
  written++;
}
await browser.close();

// React Native can't resolve URLs at runtime, so Metro needs a static require() per file.
const urls = [...jobs.keys()].sort();
writeFileSync(
  join(root, 'src/native.ts'),
  `// Generated by scripts/generate.ts — do not edit.\n/* eslint-disable */\nexport const demoImages: Record<string, number> = {\n${urls.map((u) => `  '${u}': require('../public/${u}'),`).join('\n')}\n};\n`,
);

if (sheet) {
  const html = `<body style="margin:0;display:grid;grid-template-columns:repeat(10,160px);gap:4px;font:10px sans-serif">${names.map(([u, n]) => `<div><img src="public/${u}" width="160" height="160"><div>${n}</div></div>`).join('')}</body>`;
  writeFileSync(join(root, 'sheet.html'), html);
}
console.log(`${jobs.size} images, ${written} written${unmatched.length ? `; generic art for: ${unmatched.join(', ')}` : ''}`);
